"""Stable facade for fixed-shape transcription refusal builders."""

from .refusal_export import (
    export_input_invalid,
    export_inputs_incompatible,
    timing_required_for_format,
)
from .refusal_request import (
    Refusal,
    backend_failed,
    capability_unknown,
    capability_unsatisfiable_on_stack,
    capability_unsupported,
    command_path_argument,
    input_required,
    option_unsupported_on_stack,
    option_value_unsupported,
    output_exists,
    output_is_canonical_input,
    output_path_invalid,
    output_required_for_force,
    package_build_unusable,
    package_integrity_failed,
    packages_not_provisioned,
    pin_conflicts_with_native_capability,
    range_invalid,
    run_incomplete,
    stack_required,
)

__all__ = [
    "Refusal",
    "backend_failed",
    "capability_unknown",
    "capability_unsatisfiable_on_stack",
    "capability_unsupported",
    "command_path_argument",
    "export_input_invalid",
    "export_inputs_incompatible",
    "input_required",
    "option_unsupported_on_stack",
    "option_value_unsupported",
    "output_exists",
    "output_is_canonical_input",
    "output_path_invalid",
    "output_required_for_force",
    "package_build_unusable",
    "package_integrity_failed",
    "packages_not_provisioned",
    "pin_conflicts_with_native_capability",
    "range_invalid",
    "run_incomplete",
    "stack_required",
    "timing_required_for_format",
]
